### ISSUE TITLE
模块“"umi"”没有导出的成员“useThemeConfig”。

### ISSUE THREAD

**Issue by brucethomaswayne6** [xiaohuoni/umi-plugin-antd-style#2]
<img width="1026" alt="image" src="https://github.com/xiaohuoni/umi-plugin-antd-style/assets/52198079/db13a741-225c-4eaf-9dab-008ab147ee45">

**Comment by xiaohuoni** [comment]
这个 as 只是一个文档。没有实际意义。告诉你这里面可以写的配置内容。

**Comment by xiaohuoni** [comment]
配置争取正确的话，运行一下 dev 就有这个对象了

**Comment by brucethomaswayne6** [comment]
okok, 已经跑起来了
